apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
        - name: cloud-app
          image: anishpokhrel/cloud-tag:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8083