apiVersion: v1
kind: Service
metadata:
  name: cloud-app #name of the service
spec:
  type: LoadBalancer
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083